'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pppppppFix

    '''<summary>
    '''lbParentAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbParentAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnIncParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncParent As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtIncParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncParent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubPInc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubPInc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDecParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDecParent As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtDecParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDecParent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubPDec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubPDec As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendRequest As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnViewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbpercentageProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbpercentageProgress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''childnameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents childnameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''childIDlb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents childIDlb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''govAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents govAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnIncGov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncGov As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtGovermnmentAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGovermnmentAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubGInc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubGInc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDecGov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDecGov As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtDecGov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDecGov As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubGDec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubGDec As Global.System.Web.UI.WebControls.Button
End Class
